config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  root to: 'pages#home'
  resources :user_selections, only: [:new, :create, :edit, :update] do
    resources :tech_stack, only: [:show]
  end
  resources :user_selections, only: [:destroy]

  get 'dashboard', to: 'dashboards#show'
  post "/approve/:id" => "matches#approve", as: :approve_user
  post "/decline/:id" => "matches#decline", as: :decline_user

  resources :matches, only: [:show, :create, :index] do
    resources :match_messages, only: :create
  end
  resources :posts do
    resources :comments, only: [ :index, :new, :create ]
  end
  resources :comments, only: [ :show, :edit, :update, :destroy ]
  resources :notifications, only: [:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "WUBBA", root_path, class: "wubba" %>
<!--   <a class="wubba">WUBBA</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if current_user.matches.last.present? %>
        <%= link_to "Matches", match_path(current_user.matches.last), class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Search partner", matches_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
<!--       <li class="nav-item">
        <%= link_to "LOGIN", new_user_session_path, class: "login" %>
      </li>
      <li class="nav-item">
        <%= link_to "SIGN UP", new_user_registration_path, class:"btn-primary sign" %>
      </li> -->
      <% end %>
    </ul>
  </div>

    <div class="pictures">
      <%= link_to dashboard_path do %>
        <% if user_signed_in? %>
        <i class="far fa-bell fa-lg" ></i>
          <span class="badge badge-danger js-notification-count fa-sm"><%= current_user.notifications.unread.count %></span>
        <% end %>
      <% end %>
    <% if user_signed_in? %>
      <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle" %>
    <% end %>
    </div>
</div>