config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  root to: 'pages#home'
  resources :user_selections, only: [:new, :create, :edit, :update] do
    resources :tech_stack, only: [:show]
  end
  resources :user_selections, only: [:destroy]

  get 'dashboard', to: 'dashboards#show'
  post "/approve/:id" => "matches#approve", as: :approve_user
  post "/decline/:id" => "matches#decline", as: :decline_user

  resources :matches, only: [:show, :create, :index] do
    resources :match_messages, only: :create
  end
  resources :posts do
    resources :comments, only: [ :index, :new, :create ]
  end
  resources :comments, only: [ :show, :edit, :update, :destroy ]
  resources :notifications, only: [:index]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user
    unread_notifications = current_user.notifications.unread
    unread_notifications.each do |unread_notification|
      unread_notification.read_at = DateTime.current.to_date
      unread_notification.save
    end
    set_notifications
  end

  private

  def set_notifications
    @notifications = Notification.where(recipient: current_user).reverse
  end
end

app/views/dashboards/show.html.erb
<ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tab8list">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Profile</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
<!-- Notifications -->
<h1 style="
    text-align: center;
  color: #FF385C;
  font-weight: bold;
  letter-spacing: 0.08rem;
">Notifications</h1>
<div id="notifications">
  <% @notifications.each do |notification| %>
  <%= render 'notifications/notification', notification: notification %>
  <% end %>
</div>
  </div>
  <!-- Profile -->
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
    <div class="card-white">
      <div class="shadow dashboard-profile">
        <h1> Profile </h1>
        <div class="profile">
          <% if @user.avatar.attached? %>
          <%= cl_image_tag(@user.avatar.key, class: "avatarimg", :transformation=>[
            {:width=>400, :height=>400, :gravity=>"face", :crop=>"crop"},
            {:width=>350, :crop=>"scale"}
            ]) %>
            <% end %>
            <div class="name">
              <h2> <%= @user.first_name %> </h2>
            </div>
            <div class="cards">
              <div class="box">
                <h5> Location: </h5>
                <p><%= @user.city %>, <%= @user.country %></p>
              </div>
              <div class="box">
                <h5> Age </h5>
                <p> <%= @user.age %></p>
              </div>
              <div class="box">
                <h5> City </h5>
                <p> <%= @user.city %></p>
              </div>
              <div class="box">
                <h5> Experience </h5>
                <p> <%= @user.experience_level %></p>
              </div>
            </div>
            <div class="box">
                <h5> Tech Stack </h5>
                <% @user.tech_stacks.each do |tech_stack| %>
                <%= tech_stack.name %>
                <% end %>
              </br>
            </br>
              <%= link_to "Add Stack", new_user_selection_path, class: "btn-primary sign", style: "text-align: center" %>
  <!--               <%= link_to new_user_selection_path do %>
                <h3> Add Stack </h3> -->
              <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>