config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  root to: 'pages#home'
  resources :user_selections, only: [:new, :create, :edit, :update] do
    resources :tech_stack, only: [:show]
  end
  resources :user_selections, only: [:destroy]

  get 'dashboard', to: 'dashboards#show'
  post "/approve/:id" => "matches#approve", as: :approve_user
  post "/decline/:id" => "matches#decline", as: :decline_user

  resources :matches, only: [:show, :create, :index] do
    resources :match_messages, only: :create
  end
  resources :posts do
    resources :comments, only: [ :index, :new, :create ]
  end
  resources :comments, only: [ :show, :edit, :update, :destroy ]
  resources :notifications, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :description, presence: true
  validates :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(params[:user_id])
    @post.user = @user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    @post.update(post_params)
  end

  def destroy
    @post.destroy
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :date, :title)
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<%= f.input :title  %>
<%= f.input :description  %>
<%= f.button :submit, "Posts", class: "btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Update Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="card-white">
  <h1 class="my-4"> All Posts </h1>

  <% @posts.each do |post| %>
    <div style="margin-top: 10px;margin-bottom: 10px;">
      <div class="border"></div>
    </div>

    <div class="card-product-all my-3">
      <%= cl_image_tag post.user.avatar.key, class:"post-image" %>

      <div class="card-product-infos">
        <h2> <%= link_to post.title, post_path(post) %> </h2>
        <p> Posted by: <%= post.user.first_name %> <%= post.user.last_name %> </p>
        <p> Date posted: <%= post.date %> </p>

        <div style="margin-top: 12px;margin-bottom: 24px;">

        <div class="border"></div>
        </div>

        <div class="card-white">
         <p> <%= post.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="card-white">
  <%= link_to posts_path do %>
        <p class="back-link mt-3">Back</p>
        <% end %>
  <h1 class="mt-4 mc-3" > Posts </h1>
    <div class="card-product">
      <!-- change to user avatar pic -->
      <%= cl_image_tag @post.user.avatar.key, class:"post-image" %>
      <div class="card-product-infos">
         <% if current_user == @post.user %>
         <% elsif  Match.find_by(matcher: current_user, matchee: @post.user).nil? && Match.find_by(matchee: current_user, matcher: @post.user, status: [0, 2]).nil? %>
          <%= link_to matches_path(match: { matchee_id: @post.user.id, status: 1 }, request: "post" ), method: :post do %>
          <i class="fas fa-user-plus fa-2x mb-2 pink-friend"></i>
          <% end %>
        <% end %>
        <h2> <%= @post.title %> </h2>
        <p> Posted by: <%= @post.user.first_name %> <%= @post.user.last_name %> </p>
        <p>  Date posted: <%= @post.date %></p>
      </div>
    </div>
    <div class="card-product">
      <p style="
    padding: 12px;
    font-size: 16px;"> <%= @post.description %> </p>
    </div>
        <div class="postbutton">
    <% if current_user == @post.user %>
      <%= link_to 'Edit Post', edit_post_path(@post), class:"btn btn-secondary" %>
      <%= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to remove this post?'}, class:"btn btn-danger" %>
    <!-- have on under posted date - have a friend icon -->
    <% end %>
    </div>
     <div style="margin-top: 10px;margin-bottom: 10px;">
    <div class="border"></div>
  </div>
<!--     <div class="card-product-infos">
      <h2>Comments</h2>
    </div> -->


    <div class="card-product-infos">
      <% @post.comments.each do |comment| %>
      <p style="font-weight: bold;"> <%= comment.user.username %></p>
      <p><%= comment.reply %> </p>
      <% end %>
    </div>
    <br>
    <div class="chat-box">
      <%= simple_form_for [@post, @comment] do |f| %>
    <div class="card-product-infos d-flex chat-line">
      <%= f.input :reply, label: false, placeholder: "Comment" %>
      <%= f.submit ">", class: "btn-chat btn-primary" %>
    <% end %>
    </div>
  </div>
</div>